Lab5/TODO/TODO/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

Lab5/TODO/main/urls.py
from django.urls import path
from rest_framework_jwt.views import obtain_jwt_token
from main.views import TasksViewSet, TaskViewSet, ListViewSet
from rest_framework import routers

from . import views

router = routers.SimpleRouter()
router.register('todos', TasksViewSet, basename='main')
router.register('todos', TaskViewSet, basename='main')
router.register('', ListViewSet, basename='main')

urlpatterns = [
      path('login/', obtain_jwt_token)
]
urlpatterns += router.urls

Lab5/TODO/main/models.py
from django.db import models
from django.contrib.auth.base_user import BaseUserManager
# Create your models here.
from django import forms
from django.contrib.auth.models import PermissionsMixin

from TODO import settings
from django.db import models
from django.contrib.auth.models import AbstractUser




class MainUser(AbstractUser):
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)

    class Meta:
        verbose_name = ('user')
        verbose_name_plural = ('users')

class Todos(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True, verbose_name='Название')

    class Meta:
        verbose_name = 'Лист'
        verbose_name_plural = 'Листы'
    def __str__(self):
        return self.name

class Tasks(models.Model):
    task = models.CharField(max_length=255, null=True, blank=True, verbose_name='Название')
    created_date = models.DateField(verbose_name='Дата создания')
    due_on = models.DateField(verbose_name='Дата оканчания')
    owner = models.ForeignKey(MainUser, on_delete=models.RESTRICT, related_name='owner', verbose_name='Владелец')
    mark = models.BooleanField(verbose_name='Статус')
    todos = models.ForeignKey(Todos, on_delete=models.RESTRICT, related_name='todos', verbose_name='Лист')

    class Meta:
        ordering = ['id']
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

Lab5/TODO/main/views.py
from django.shortcuts import render
from .models import Todos, Tasks, MainUser
from rest_framework import generics, mixins, viewsets
from main.serializers import TodosSerializer, TaskSerializer, MainUserSerializer, TasksSerializer
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework.response import Response
from rest_framework.decorators import action
# # Create your views here.

class TasksViewSet(generics.ListAPIView, generics.UpdateAPIView, generics.DestroyAPIView, viewsets.ViewSet):
    permission_classes = (IsAuthenticated)
    serializer_class = TasksSerializer
    queryset = Tasks.objects.all()

    def get_queryset(self):
        return Tasks.objects.filter(mark=False)

    def get_permissions(self):
        permission_classes = (IsAuthenticated,)
        return [permission() for permission in permission_classes]


    @action(methods=['GET'], detail=True, url_path='completed', url_name='active')
    def active(self, request, pk):
        queryset = Tasks.objects.filter(todos_id=pk, mark=True)
        serializer = TasksSerializer(queryset, many=True)
        return Response(serializer.data)


class TaskViewSet(viewsets.ModelViewSet):
    permission_classes = (IsAuthenticated)
    serializer_class = TaskSerializer
    queryset = Tasks.objects.all()
    def get_permissions(self):
        permission_classes = (IsAuthenticated,)
        return [permission() for permission in permission_classes]


class ListViewSet(viewsets.ModelViewSet):
    permission_classes = (IsAuthenticated)
    serializer_class = TodosSerializer
    queryset = Todos.objects.all()
    def get_permissions(self):
        permission_classes = (IsAuthenticated,)
        return [permission() for permission in permission_classes]

Lab5/TODO/templates/base.html
{% load static%}
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type = "text/css" href="{% static 'css/todo_list.css'%}"/>
    <title>Todo List</title>
</head>
<body>
    <div class="app_bar"><p>BFDjango TODO</p></div>
    <div class="main_part">
    <button class="task_add">Add Task</button>
    {% block content %}
    {% endblock %}


    </div>


</body>


</html>

Lab5/TODO/templates/completed_todo_list.html
{% extends 'base.html' %}
{% block content %}
 <table class="equal-width-cols">
    <tr>
        <th  style="font-size: 36px">
    Completed tasks in {{ todo.name }}
        </th>
   </tr>
</table>
    <table class="equal-width-cols">
        <tr >
      <th scope="col" >Task</th>
      <th scope="col">Created</th>
      <th scope="col">Due on</th>
      <th scope="col">Owner</th>
       <th scope="col">Mark</th>

    </tr>

	{% for curtask in tasks_list %}


			<td style="color: #598FFB">{{ curtask.task }}</td>
			<td>{{ curtask.created_date|date:"d/m/Y" }}</td>
			<td>{{ curtask.due_on|date:"d/m/Y"  }}</td>
			<td >{{ curtask.owner }}</td>
			<td ><div class="status">Done</div></td>


       </tr>


       {% endfor%}

</table>
    <a href="http://localhost:8000/{{ todo.id }}/todos" class="view_complete">View incomplete tasks</a>
    <button class="delete">Delete this list</button>
{% endblock %}

Lab5/TODO/templates/todo_list.html
{% extends 'base.html' %}
{% block content %}
    <table class="equal-width-cols">
    <tr>
        <th  style="font-size: 36px">

    Tasks in "{{ todo.name }}"

        </th>
   </tr>
</table>
    <table class="equal-width-cols">
        <tr >
      <th scope="col" >Task</th>
      <th scope="col">Created</th>
      <th scope="col">Due on</th>
      <th scope="col">Owner</th>
       <th scope="col">Mark</th>

    </tr>
 {% for curtask in tasks_list %}


			<td style="color: #598FFB">{{ curtask.task }}</td>
			<td>{{ curtask.created_date| date:"d/m/Y" }}</td>
			<td>{{ curtask.due_on| date:"d/m/Y" }}</td>
			<td >{{ curtask.owner }}</td>


			<td ><div class="status">Not Done</div></td>

       </tr>

       {% endfor%}

</table>
    <a href="/todos/{{ todo.id}}/completed/" class="view_complete">View completed tasks</a>
    <button class="delete">Delete this list</button>
{% endblock %}

Lab5/TODO/templates/todos.html
{% extends 'base.html' %}
{% block content %}
    <table class="equal-width-cols">
    <tr>
        <th  style="font-size: 36px">
    List of To-Do
        </th>
   </tr>
</table>
    <table class="equal-width-cols">
        <tr >
      <th scope="col" >List</th>
    </tr>

	{% for curTodo in todos %}
        <td ><a  style="text-decoration: none; color: #598FFB" href="{{curTodo.id}}/todos">{{ curTodo }}</a></td>
       </tr>
       {% endfor%}

</table>
{% endblock %}